version: '3.8'

services:
  postgres:
    container_name: cart_db
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=cart
    ports:
      - 5436:5432
    volumes:
      - /var/lib/docker/volumes/pgdata/_data

    